# Header

menu:
  主页: /
  随笔: /tags/随笔/
  #类别: /categories/Hexo教程
  技术: /tags/技术/
  文章归档: /archives
  相册: /photos
  #云标签: /tagcloud
  
# SubNav
subnav:
  github: "https://github.com/wujiyang"
  #weibo: "#"
  rss: "/atom.xml"
  zhihu: "https://www.zhihu.com/people/wujiyang/activities"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #mail: "1441615466@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
# 文章太长，截断按钮文字
excerpt_link: Reading More
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

#文章导航功能
toc: true
#是否开启云标签,没有找到选项
#tagcloud: true

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
# 打赏wording
reward_wording: '谢谢打赏，继续努力'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: "http://p1.bpimg.com/567571/0dde3e062ded6e2f.jpg"
# 微信二维码图片地址
weixin: "http://p1.bqimg.com/567571/376d50f0e60de5ca.jpg"

# Miscellaneous
# github屏蔽了baiduspyder，所以无法进行站长统计分析，可以加入google分析
baidu_analytics: 'a34910709550b7a8ae7cf9fabe5a2429'
google_analytics: ''
favicon: /favicon.png

#你的头像url
#avatar: "http://ww2.sinaimg.cn/large/7f318987jw1f72m7gv450j205k05kmx1.jpg"
avatar: http://i1.piimg.com/567571/8edc35a4e7c8921c.jpg
#是否开启分享
share_jia: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: wujiyang

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友情链接'
  aboutme: '关于我'

friends:
  CSDN-邬小阳: http://my.csdn.net/u013078356/
  GitHub-邬小阳: https://github.com/wujiyang/
  ZhiHu-邬小阳: https://www.zhihu.com/people/wujiyang/activities/
  友情链接4: http://localhost:4000/
  友情链接5: http://localhost:4000/
  友情链接6: http://localhost:4000/


aboutme: >
 华中科技大学计算机学院<br>
 渣渣小硕一枚<br>
 正在程序猿的道路上踽踽前行<br>
 -<br>
 -<br>
 虚拟世界<br>
 你是内存中哪一个孤独的进程?<br>
 现实社会<br>
 你是人群中哪一个平凡的身影?<br>
 此端，彼岸<br>
 生活在编码与健身中切换